name: 'bkk_pipeline'
version: '1.0.0'
config-version: 2
profile: 'databricks'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  bkk_pipeline:
    silver:
      +materialized: incremental
      +file_format: delta
      +incremental_strategy: merge
    gold:
      +materialized: table
      +file_format: delta